# Generated by Django 3.0.2 on 2020-02-05 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsc',
            name='custom',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), size=None),
        ),
    ]
