# Generated by Django 3.0.2 on 2020-04-21 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_connect_app', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsc',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dsc',
            name='custom',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='dsc',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='dsc',
            name='quote',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
