# Generated by Django 3.0.2 on 2020-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_connect_app', '0002_auto_20200205_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsc',
            name='custom',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dsc',
            name='domains',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
