# Generated by Django 3.0.2 on 2020-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_connect_app', '0003_auto_20200205_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsc',
            name='status',
            field=models.CharField(choices=[('0', 'draft'), ('1', 'published')], default='0', max_length=1),
        ),
    ]
